<a href="https://colab.research.google.com/github/hyunicecream/ML-DL/blob/main/XGB(for%20Regression)(Boston_husing_kaggle).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('house.csv')
df

        Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0        1          60       RL  ...        WD         Normal    208500
1        2          20       RL  ...        WD         Normal    181500
2        3          60       RL  ...        WD         Normal    223500
3        4          70       RL  ...        WD        Abnorml    140000
4        5          60       RL  ...        WD         Normal    250000
...    ...         ...      ...  ...       ...            ...       ...
1455  1456          60       RL  ...        WD         Normal    175000
1456  1457          20       RL  ...        WD         Normal    210000
1457  1458          70       RL  ...        WD         Normal    266500
1458  1459          20       RL  ...        WD         Normal    142125
1459  1460          20       RL  ...        WD         Normal    147500

[1460 rows x 81 columns]

In [ ]:
# Null 값 확인하기
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [ ]:
# null > 0 으로 정렬하기, 내림차순으로
null = df.isnull().sum()
null[null > 0].sort_values(ascending = False)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageYrBlt       81
GarageType        81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtFinType1      37
BsmtCond          37
BsmtQual          37
MasVnrArea         8
MasVnrType         8
Electrical         1
dtype: int64

In [ ]:
# 불필요한 컬럼과 Null 값이 많은 컬럼을 삭제한다.
df.drop(['Id', 'PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'LotFrontage'
        ,'GarageYrBlt', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'
        ,'BsmtFinType2', 'BsmtExposure', 'BsmtFinType1', 'BsmtCond', 'BsmtQual'
        ,'MasVnrArea', 'MasVnrType', 'Electrical'], axis=1, inplace=True)

In [ ]:
# 숫자형이 아니면 categorical로 변환하고, 숫자형은 결측치를 평균으로 대체한다.
enc = {}
for feat in df.columns:
    # categorical로 변환한다. 역변환이 가능하도록 LabelEncoder를 딕셔너리에 보관해 둔다.
    if df[feat].dtype == object:
        enc[feat] = LabelEncoder()
        df[feat] = enc[feat].fit_transform(df[feat].astype(str))
    
    # 결측치를 평균으로 대체한다.
    # elif df[feat].dtype == 'int64' or df[feat].dtype == 'float64':
    else:
        df[feat].fillna(df[feat].mean(), inplace = True)
df.head()

   MSSubClass  MSZoning  LotArea  ...  SaleType  SaleCondition  SalePrice
0          60         3     8450  ...         8              4     208500
1          20         3     9600  ...         8              4     181500
2          60         3    11250  ...         8              4     223500
3          70         3     9550  ...         8              0     140000
4          60         3    14260  ...         8              4     250000

[5 rows x 61 columns]

In [ ]:
# 학습시키기위해 target과 features를 정해준다.
target = df['SalePrice']
features = df.drop('SalePrice', axis=1)

In [ ]:
# 학습데이터를 구성한다.
trainX, testX, trainY, testY = train_test_split(features, target, test_size = 0.2)

In [ ]:
# XGBoost (regressor)로 Train 데이터 세트를 학습한다.
model = XGBRegressor(objective='reg:squarederror')  # default로 학습
model.fit(trainX, trainY)

XGBRegressor(objective='reg:squarederror')

In [ ]:
# 테스트 데이터 전체의 R-sequare
# R-score가 1에 가까울 수록 상관관계
# R-score가 0에 가까울 수록 상관관계 X
print('R-square = %.4f' % model.score(testX, testY))

R-square = 0.8964